import { numeric, pgEnum, pgTable, text, timestamp } from "drizzle-orm/pg-core";
import { organizations } from "./platform";

/**
 * Accounts — Receivables leg, seeded from a real trigger (dispatch documentation for a
 * Sales Order) rather than designed in the abstract. This is deliberately narrow: one
 * `invoices` row per order, capturing the E-way Bill/Invoice/supporting documents and the
 * final billed value (base order value, plus freight when TMS's own shipment was
 * Self-arranged — see `src/db/schema/tms.ts`'s own header comment). No GL, no aging, no
 * multi-invoice-per-order split yet.
 *
 * Reuses `order_payments` (src/db/schema/orders.ts) for what's actually been collected —
 * that table was already built during Order FMS specifically so a future Accounts module
 * would have this foundation rather than needing a second payments table. Payables (against
 * a Purchase PO) is a separate, still entirely unscoped extension — this file is the
 * Receivables side only.
 */
export const invoiceStatusEnum = pgEnum("invoice_status", ["Draft", "Issued"]);

export const invoices = pgTable("invoices", {
  // Invoice_ID, e.g. "INV-xxxx" — the real key. invoiceNo is the actual, human-facing
  // invoice number as issued (a business/GST document number, not necessarily generated by
  // this app — free text so it can match whatever numbering series/software actually
  // produced the document).
  id: text("id").primaryKey(),
  orgId: text("org_id")
    .notNull()
    .references(() => organizations.id),
  orderId: text("order_id").notNull(),
  invoiceNo: text("invoice_no").notNull().default(""),
  invoiceAttachmentUrl: text("invoice_attachment_url").notNull().default(""),
  ewayBillNo: text("eway_bill_no").notNull().default(""),
  ewayBillAttachmentUrl: text("eway_bill_attachment_url").notNull().default(""),
  // Optional — a packing list, quality certificate, whatever else the customer needs.
  extraDocumentUrl: text("extra_document_url").notNull().default(""),
  // Base order value + freight if applicable — what is actually billed, confirmed by the
  // Doer. Deliberately separate from orders.orderValue (a snapshot Order FMS's own credit
  // gate depends on staying stable) rather than overwriting it.
  finalValue: numeric("final_value").notNull().default("0"),
  status: invoiceStatusEnum("status").notNull().default("Draft"),
  issuedBy: text("issued_by").notNull().default(""),
  issuedAt: timestamp("issued_at", { withTimezone: true }),
  createdBy: text("created_by").notNull().default(""),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});
