import {
  boolean,
  index,
  integer,
  numeric,
  pgEnum,
  pgTable,
  primaryKey,
  text,
  timestamp,
  unique,
} from "drizzle-orm/pg-core";
import { organizations } from "./platform";
import { orderPaymentModeEnum } from "./orders";

/**
 * Accounts — Receivables leg, seeded from a real trigger (dispatch documentation for a
 * Sales Order) rather than designed in the abstract. This is deliberately narrow: one
 * `invoices` row per order, capturing the E-way Bill/Invoice/supporting documents and the
 * final billed value (base order value, plus freight when TMS's own shipment was
 * Self-arranged — see `src/db/schema/tms.ts`'s own header comment). No GL, no aging, no
 * multi-invoice-per-order split yet.
 *
 * Reuses `order_payments` (src/db/schema/orders.ts) for what's actually been collected —
 * that table was already built during Order FMS specifically so a future Accounts module
 * would have this foundation rather than needing a second payments table. Payables (against
 * a Purchase PO) is a separate, still entirely unscoped extension — this file is the
 * Receivables side only.
 */
export const invoiceStatusEnum = pgEnum("invoice_status", ["Draft", "Issued"]);

export const invoices = pgTable(
  "invoices",
  {
  // Invoice_ID, e.g. "INV-xxxx" — the real key. invoiceNo is the actual, human-facing
  // invoice number as issued (a business/GST document number, not necessarily generated by
  // this app — free text so it can match whatever numbering series/software actually
  // produced the document).
  id: text("id").primaryKey(),
  orgId: text("org_id")
    .notNull()
    .references(() => organizations.id),
  orderId: text("order_id").notNull(),
  invoiceNo: text("invoice_no").notNull().default(""),
  invoiceAttachmentUrl: text("invoice_attachment_url").notNull().default(""),
  ewayBillNo: text("eway_bill_no").notNull().default(""),
  ewayBillAttachmentUrl: text("eway_bill_attachment_url").notNull().default(""),
  // Optional — a packing list, quality certificate, whatever else the customer needs.
  extraDocumentUrl: text("extra_document_url").notNull().default(""),
  // Base order value + freight if applicable — what is actually billed, confirmed by the
  // Doer. Deliberately separate from orders.orderValue (a snapshot Order FMS's own credit
  // gate depends on staying stable) rather than overwriting it.
  finalValue: numeric("final_value").notNull().default("0"),
  // GST portion of finalValue, snapshotted from orders.gstAmount at creation time (capped
  // to finalValue) — lets issueInvoice() book GST collected to its own liability account
  // (GST Payable) instead of folding it into Sales Revenue. "0" for an invoice created
  // before this column existed, which keeps posting it the old (pre-GST-split) way.
  gstAmount: numeric("gst_amount").notNull().default("0"),
  status: invoiceStatusEnum("status").notNull().default("Draft"),
  issuedBy: text("issued_by").notNull().default(""),
  issuedAt: timestamp("issued_at", { withTimezone: true }),
  createdBy: text("created_by").notNull().default(""),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    // A real uniqueness constraint, not just an index — closes a check-then-insert race
    // that could otherwise create two Draft invoices for the same order (found during the
    // 2026-09-24 accounting review; matches the retry-on-collision pattern this codebase
    // already uses for quotations.quotationNo/dispatches.gatePassNo).
    unique("invoices_org_id_order_id_unique").on(table.orgId, table.orderId),
  ]
);

/**
 * The General Ledger (2026-09-22) — real double-entry bookkeeping underneath Receivables
 * (`invoices` above, `order_payments` in orders.ts) and Payables (`bills`/`bill_payments`
 * below), rather than either standing alone as an isolated document log. `chart_of_accounts`
 * is seeded per org with a small default set (`seedDefaultChartOfAccounts()` in
 * src/lib/accounts/ledger.ts) an Admin can extend; `is_system` marks the seeded rows so
 * they can't be deleted out from under the auto-posting logic that assumes they exist.
 *
 * A journal entry always balances (sum of debits = sum of credits across its lines) —
 * enforced in application code (`postJournalEntry()`), not by a DB constraint, since
 * Drizzle/Postgres has no clean way to check a cross-row sum at insert time here. Every
 * entry is posted automatically from a real business event (an invoice issued, a bill
 * issued, a payment recorded either direction) via `sourceType`/`sourceId`, or created
 * directly for a manual adjustment — never edited or deleted after posting, matching every
 * other append-only timeline in this schema (`lead_activities`, `order_activities`, ...);
 * a correction is its own new, reversing entry.
 */
export const accountTypeEnum = pgEnum("account_type", [
  "Asset",
  "Liability",
  "Equity",
  "Income",
  "Expense",
]);

export const chartOfAccounts = pgTable(
  "chart_of_accounts",
  {
    // Account_ID, e.g. "ACC-xxxx".
    id: text("id").primaryKey(),
    orgId: text("org_id")
      .notNull()
      .references(() => organizations.id),
    code: text("code").notNull().default(""),
    name: text("name").notNull(),
    type: accountTypeEnum("type").notNull(),
    // Seeded by seedDefaultChartOfAccounts() — the auto-posting logic below hard-codes
    // which of these it debits/credits, so a system account is not user-deletable.
    isSystem: boolean("is_system").notNull().default(false),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [unique("chart_of_accounts_org_id_code_unique").on(table.orgId, table.code)]
);

export const journalEntries = pgTable(
  "journal_entries",
  {
    // Journal_Entry_ID, e.g. "JE-xxxx".
    id: text("id").primaryKey(),
    orgId: text("org_id")
      .notNull()
      .references(() => organizations.id),
    entryDate: timestamp("entry_date", { withTimezone: true }).notNull().defaultNow(),
    description: text("description").notNull().default(""),
    // "Invoice" | "Bill" | "ReceivablePayment" | "PayablePayment" | "Manual" — which real
    // event produced this entry, and the row in that table, so a report can link back to
    // the source document rather than just showing a number.
    sourceType: text("source_type").notNull().default(""),
    sourceId: text("source_id").notNull().default(""),
    createdBy: text("created_by").notNull().default(""),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    // getTrialBalance() (Trial Balance/P&L/Balance Sheet, all live-computed) filters and
    // range-queries exactly this shape.
    index("journal_entries_org_id_entry_date_idx").on(table.orgId, table.entryDate),
  ]
);

/** One row per debit/credit line, grouped by Journal_Entry_ID — same flat-rows-by-group
 * shape as `quotation_items`/`bom`, composite PK (entry_id, line_no). Exactly one of
 * debit/credit is non-zero on any given line; which one is which account is what encodes
 * the actual accounting meaning, not a sign. */
export const journalLines = pgTable(
  "journal_lines",
  {
    entryId: text("entry_id").notNull(),
    orgId: text("org_id")
      .notNull()
      .references(() => organizations.id),
    lineNo: integer("line_no").notNull(),
    accountId: text("account_id").notNull(),
    debit: numeric("debit").notNull().default("0"),
    credit: numeric("credit").notNull().default("0"),
  },
  (table) => [
    primaryKey({ columns: [table.entryId, table.lineNo] }),
    index("journal_lines_org_id_idx").on(table.orgId),
  ]
);

/**
 * Payables — the mirror of Receivables above, against a Purchase Order (`purchase_orders`
 * in purchase.ts) instead of a Sales Order. Deliberately the same narrow shape `invoices`
 * used before the GL existed: one bill per PO, an append-only payment log
 * (`bill_payments`, mirroring `order_payments` exactly, down to reusing its own
 * `orderPaymentModeEnum` rather than declaring a second identical Postgres enum type).
 */
export const billStatusEnum = pgEnum("bill_status", ["Draft", "Issued"]);

export const bills = pgTable(
  "bills",
  {
  // Bill_ID, e.g. "BILL-xxxx".
  id: text("id").primaryKey(),
  orgId: text("org_id")
    .notNull()
    .references(() => organizations.id),
  poId: text("po_id").notNull(),
  vendorId: text("vendor_id").notNull(),
  // The vendor's own invoice/bill number — free text, same reasoning as invoices.invoiceNo.
  billNo: text("bill_no").notNull().default(""),
  billAttachmentUrl: text("bill_attachment_url").notNull().default(""),
  amount: numeric("amount").notNull().default("0"),
  status: billStatusEnum("status").notNull().default("Draft"),
  issuedBy: text("issued_by").notNull().default(""),
  issuedAt: timestamp("issued_at", { withTimezone: true }),
  createdBy: text("created_by").notNull().default(""),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    // Same reasoning as invoices_org_id_order_id_unique above — one bill per PO, enforced
    // for real rather than only by a check-then-insert race in application code.
    unique("bills_org_id_po_id_unique").on(table.orgId, table.poId),
  ]
);

/**
 * Additional Payments (2026-09-24) — a one-off Cash/Bank expense not tied to any Sales or
 * Purchase document (rent, salaries, utilities, misc.) — the gap between Receivables/
 * Payables (both anchored to an order/PO) and a genuine day-to-day business expense.
 * `categoryAccountId` is always an Expense-type `chart_of_accounts` row (seeded defaults:
 * Rent/Salary/Utilities/Misc Expense, see ledger.ts's SYSTEM_ACCOUNT_CODES) — always paid
 * from the main Cash/Bank account; a Petty-Cash-funded expense is recorded in
 * `petty_cash_entries` below instead, not here. Posted to the GL atomically at creation
 * (no Draft/Issued step — unlike an Invoice, there's no document to complete afterwards,
 * the expense simply happened).
 */
export const expenseEntries = pgTable(
  "expense_entries",
  {
    // Expense_ID, e.g. "EXP-xxxx".
    id: text("id").primaryKey(),
    orgId: text("org_id")
      .notNull()
      .references(() => organizations.id),
    entryDate: timestamp("entry_date", { withTimezone: true }).notNull().defaultNow(),
    categoryAccountId: text("category_account_id").notNull(),
    description: text("description").notNull().default(""),
    paidTo: text("paid_to").notNull().default(""),
    amount: numeric("amount").notNull(),
    attachmentUrl: text("attachment_url").notNull().default(""),
    createdBy: text("created_by").notNull().default(""),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [index("expense_entries_org_id_idx").on(table.orgId, table.entryDate)]
);

// PettyCashEntryRecord.Kind — TopUp moves money INTO Petty Cash from Cash/Bank (or another
// source); Expense moves money OUT of Petty Cash against an Expense category account. Same
// shape either way (a counter account + amount + description) so the book reads as one
// timeline, not two separate lists.
export const pettyCashKindEnum = pgEnum("petty_cash_kind", ["TopUp", "Expense"]);

/**
 * The Petty Cash Book (2026-09-24) — a small imprest cash fund, separate from the main
 * Cash/Bank account (its own `chart_of_accounts` Asset row, SYSTEM_ACCOUNT_CODES.PETTY_CASH),
 * topped up occasionally and spent from directly for small day-to-day cash expenses. Its
 * running balance is never stored here — same "derived, never stored" philosophy as every
 * other running total in this codebase (stock on-hand, order-reserved, customer outstanding)
 * — it's computed by summing this account's own `journal_lines` debit/credit, live, in
 * `src/lib/accounts/pettyCash.ts`.
 */
export const pettyCashEntries = pgTable(
  "petty_cash_entries",
  {
    // Petty_Cash_Entry_ID, e.g. "PCE-xxxx".
    id: text("id").primaryKey(),
    orgId: text("org_id")
      .notNull()
      .references(() => organizations.id),
    entryDate: timestamp("entry_date", { withTimezone: true }).notNull().defaultNow(),
    kind: pettyCashKindEnum("kind").notNull(),
    // TopUp: where the cash came from (normally Cash/Bank). Expense: which Expense category
    // it was spent against (Rent/Salary/Utilities/Misc, or any other Expense account).
    counterAccountId: text("counter_account_id").notNull(),
    description: text("description").notNull().default(""),
    amount: numeric("amount").notNull(),
    attachmentUrl: text("attachment_url").notNull().default(""),
    createdBy: text("created_by").notNull().default(""),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [index("petty_cash_entries_org_id_idx").on(table.orgId, table.entryDate)]
);

export const billPayments = pgTable(
  "bill_payments",
  {
    // Bill_Payment_ID, e.g. "BPY-xxxx".
    id: text("id").primaryKey(),
    orgId: text("org_id")
      .notNull()
      .references(() => organizations.id),
    billId: text("bill_id").notNull(),
    amount: numeric("amount").notNull(),
    mode: orderPaymentModeEnum("mode").notNull().default("Bank_Transfer"),
    reference: text("reference").notNull().default(""),
    paidAt: timestamp("paid_at", { withTimezone: true }).notNull().defaultNow(),
    recordedBy: text("recorded_by").notNull().default(""),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [index("bill_payments_org_id_bill_id_idx").on(table.orgId, table.billId)]
);
