import {
  boolean,
  index,
  integer,
  numeric,
  pgEnum,
  pgTable,
  primaryKey,
  text,
  timestamp,
  unique,
} from "drizzle-orm/pg-core";
import { organizations } from "./platform";
import { orderPaymentModeEnum } from "./orders";

/**
 * Accounts — Receivables leg, seeded from a real trigger (dispatch documentation for a
 * Sales Order) rather than designed in the abstract. Captures the E-way Bill/Invoice/
 * supporting documents and the final billed value (base order value, plus freight when
 * TMS's own shipment was Self-arranged — see `src/db/schema/tms.ts`'s own header comment).
 *
 * **An order can have several invoices (multi-invoice split, added 2026-09-24)** — e.g. a
 * large order billed in parts as it ships. There is deliberately NO
 * `unique(org_id, order_id)` constraint here anymore (it existed 2026-09-22 through
 * 2026-09-24, enforcing exactly one invoice per order — removed once the business need for
 * a split was confirmed). What stops double-billing now is `src/lib/accounts/accounts.ts`'s
 * own "remaining invoiceable value" check (`invoicedSoFar()`/`createInvoice()`) — the sum of
 * `finalValue` across every existing invoice for an order (Draft AND Issued) can never
 * exceed `getInvoiceSuggestion()`'s own total (order value + Self-arranged TMS freight).
 * GST is prorated across an order's invoices proportionally to each invoice's own share of
 * the order total, capped so the running sum can never exceed `orders.gstAmount` — see
 * `createInvoice()`'s/`issueInvoice()`'s own comments for the exact formula.
 *
 * Reuses `order_payments` (src/db/schema/orders.ts) for what's actually been collected —
 * that table was already built during Order FMS specifically so a future Accounts module
 * would have this foundation rather than needing a second payments table. Payables (against
 * a Purchase PO) is a separate, still entirely unscoped extension — this file is the
 * Receivables side only.
 */
export const invoiceStatusEnum = pgEnum("invoice_status", ["Draft", "Issued"]);

export const invoices = pgTable(
  "invoices",
  {
  // Invoice_ID, e.g. "INV-xxxx" — the real key. invoiceNo is the actual, human-facing
  // invoice number as issued (a business/GST document number, not necessarily generated by
  // this app — free text so it can match whatever numbering series/software actually
  // produced the document).
  id: text("id").primaryKey(),
  orgId: text("org_id")
    .notNull()
    .references(() => organizations.id),
  orderId: text("order_id").notNull(),
  invoiceNo: text("invoice_no").notNull().default(""),
  invoiceAttachmentUrl: text("invoice_attachment_url").notNull().default(""),
  ewayBillNo: text("eway_bill_no").notNull().default(""),
  ewayBillAttachmentUrl: text("eway_bill_attachment_url").notNull().default(""),
  // Optional — a packing list, quality certificate, whatever else the customer needs.
  extraDocumentUrl: text("extra_document_url").notNull().default(""),
  // This invoice's own share of the order's total billable value — confirmed by the Doer.
  // Deliberately separate from orders.orderValue (a snapshot Order FMS's own credit gate
  // depends on staying stable) rather than overwriting it. Several invoices for the same
  // order each carry their own finalValue; their sum can never exceed the order's own
  // invoiceable total — see this table's own header comment.
  finalValue: numeric("final_value").notNull().default("0"),
  // GST portion of finalValue, prorated from orders.gstAmount by this invoice's own share of
  // the order total, capped so the running sum across every invoice for the order can never
  // exceed orders.gstAmount — lets issueInvoice() book GST collected to its own liability
  // account (GST Payable) instead of folding it into Sales Revenue. "0" for an invoice
  // created before GST tracking existed, which keeps posting it the old way.
  gstAmount: numeric("gst_amount").notNull().default("0"),
  status: invoiceStatusEnum("status").notNull().default("Draft"),
  issuedBy: text("issued_by").notNull().default(""),
  issuedAt: timestamp("issued_at", { withTimezone: true }),
  createdBy: text("created_by").notNull().default(""),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [index("invoices_org_id_order_id_idx").on(table.orgId, table.orderId)]
);

/**
 * The General Ledger (2026-09-22) — real double-entry bookkeeping underneath Receivables
 * (`invoices` above, `order_payments` in orders.ts) and Payables (`bills`/`bill_payments`
 * below), rather than either standing alone as an isolated document log. `chart_of_accounts`
 * is seeded per org with a small default set (`seedDefaultChartOfAccounts()` in
 * src/lib/accounts/ledger.ts) an Admin can extend; `is_system` marks the seeded rows so
 * they can't be deleted out from under the auto-posting logic that assumes they exist.
 *
 * A journal entry always balances (sum of debits = sum of credits across its lines) —
 * enforced in application code (`postJournalEntry()`), not by a DB constraint, since
 * Drizzle/Postgres has no clean way to check a cross-row sum at insert time here. Every
 * entry is posted automatically from a real business event (an invoice issued, a bill
 * issued, a payment recorded either direction) via `sourceType`/`sourceId`, or created
 * directly for a manual adjustment — never edited or deleted after posting, matching every
 * other append-only timeline in this schema (`lead_activities`, `order_activities`, ...);
 * a correction is its own new, reversing entry.
 */
export const accountTypeEnum = pgEnum("account_type", [
  "Asset",
  "Liability",
  "Equity",
  "Income",
  "Expense",
]);

export const chartOfAccounts = pgTable(
  "chart_of_accounts",
  {
    // Account_ID, e.g. "ACC-xxxx".
    id: text("id").primaryKey(),
    orgId: text("org_id")
      .notNull()
      .references(() => organizations.id),
    code: text("code").notNull().default(""),
    name: text("name").notNull(),
    type: accountTypeEnum("type").notNull(),
    // Seeded by seedDefaultChartOfAccounts() — the auto-posting logic below hard-codes
    // which of these it debits/credits, so a system account is not user-deletable.
    isSystem: boolean("is_system").notNull().default(false),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [unique("chart_of_accounts_org_id_code_unique").on(table.orgId, table.code)]
);

export const journalEntries = pgTable(
  "journal_entries",
  {
    // Journal_Entry_ID, e.g. "JE-xxxx".
    id: text("id").primaryKey(),
    orgId: text("org_id")
      .notNull()
      .references(() => organizations.id),
    entryDate: timestamp("entry_date", { withTimezone: true }).notNull().defaultNow(),
    description: text("description").notNull().default(""),
    // "Invoice" | "Bill" | "ReceivablePayment" | "PayablePayment" | "Manual" — which real
    // event produced this entry, and the row in that table, so a report can link back to
    // the source document rather than just showing a number.
    sourceType: text("source_type").notNull().default(""),
    sourceId: text("source_id").notNull().default(""),
    createdBy: text("created_by").notNull().default(""),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    // getTrialBalance() (Trial Balance/P&L/Balance Sheet, all live-computed) filters and
    // range-queries exactly this shape.
    index("journal_entries_org_id_entry_date_idx").on(table.orgId, table.entryDate),
  ]
);

/** One row per debit/credit line, grouped by Journal_Entry_ID — same flat-rows-by-group
 * shape as `quotation_items`/`bom`, composite PK (entry_id, line_no). Exactly one of
 * debit/credit is non-zero on any given line; which one is which account is what encodes
 * the actual accounting meaning, not a sign. */
export const journalLines = pgTable(
  "journal_lines",
  {
    entryId: text("entry_id").notNull(),
    orgId: text("org_id")
      .notNull()
      .references(() => organizations.id),
    lineNo: integer("line_no").notNull(),
    accountId: text("account_id").notNull(),
    debit: numeric("debit").notNull().default("0"),
    credit: numeric("credit").notNull().default("0"),
  },
  (table) => [
    primaryKey({ columns: [table.entryId, table.lineNo] }),
    index("journal_lines_org_id_idx").on(table.orgId),
  ]
);

/**
 * Payables — the mirror of Receivables above, against a Purchase Order (`purchase_orders`
 * in purchase.ts) instead of a Sales Order. Deliberately the same narrow shape `invoices`
 * used before the GL existed: one bill per PO, an append-only payment log
 * (`bill_payments`, mirroring `order_payments` exactly, down to reusing its own
 * `orderPaymentModeEnum` rather than declaring a second identical Postgres enum type).
 *
 * `gstPercent`/`gstAmount` (added 2026-09-25, Input Tax Credit tracking) mirror
 * `invoices.gstAmount`'s own contract exactly but on the input side: `amount` is the
 * GST-INCLUSIVE total actually payable to the vendor (same as `invoices.finalValue`), and
 * `gstAmount` is the GST portion within it, extracted from `amount` at create/issue time
 * using `purchase_orders.gstPercent` as the default rate (a Bill can override it, same as a
 * PO's own gstPercent can override Purchase Setup's default). Booked to a new
 * `GST_INPUT_CREDIT` Asset account instead of folding it into Purchases/COGS — see
 * `ledger.ts`'s own `SYSTEM_ACCOUNT_CODES` comment for why this is the Payables-side mirror
 * of `GST_PAYABLE`, and what it exists for: without it, GST Report's own "Output GST minus
 * Input GST" net-payable figure would have no input side to net against.
 */
export const billStatusEnum = pgEnum("bill_status", ["Draft", "Issued"]);

export const bills = pgTable(
  "bills",
  {
  // Bill_ID, e.g. "BILL-xxxx".
  id: text("id").primaryKey(),
  orgId: text("org_id")
    .notNull()
    .references(() => organizations.id),
  poId: text("po_id").notNull(),
  vendorId: text("vendor_id").notNull(),
  // The vendor's own invoice/bill number — free text, same reasoning as invoices.invoiceNo.
  billNo: text("bill_no").notNull().default(""),
  billAttachmentUrl: text("bill_attachment_url").notNull().default(""),
  // GST-inclusive total actually payable — see this table's own header comment.
  amount: numeric("amount").notNull().default("0"),
  // Snapshotted from purchase_orders.gstPercent at Draft time (overridable) — kept alongside
  // gstAmount so a later re-derivation (e.g. if amount is edited while still Draft) has the
  // rate on hand without re-reading the PO.
  gstPercent: numeric("gst_percent").notNull().default("0"),
  gstAmount: numeric("gst_amount").notNull().default("0"),
  status: billStatusEnum("status").notNull().default("Draft"),
  issuedBy: text("issued_by").notNull().default(""),
  issuedAt: timestamp("issued_at", { withTimezone: true }),
  createdBy: text("created_by").notNull().default(""),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    // Same reasoning as invoices_org_id_order_id_unique above — one bill per PO, enforced
    // for real rather than only by a check-then-insert race in application code.
    unique("bills_org_id_po_id_unique").on(table.orgId, table.poId),
  ]
);

/**
 * Additional Payments (2026-09-24) — a one-off Cash/Bank expense not tied to any Sales or
 * Purchase document (rent, salaries, utilities, misc.) — the gap between Receivables/
 * Payables (both anchored to an order/PO) and a genuine day-to-day business expense.
 * `categoryAccountId` is always an Expense-type `chart_of_accounts` row (seeded defaults:
 * Rent/Salary/Utilities/Misc Expense, see ledger.ts's SYSTEM_ACCOUNT_CODES) — always paid
 * from the main Cash/Bank account; a Petty-Cash-funded expense is recorded in
 * `petty_cash_entries` below instead, not here. Posted to the GL atomically at creation
 * (no Draft/Issued step — unlike an Invoice, there's no document to complete afterwards,
 * the expense simply happened).
 */
export const expenseEntries = pgTable(
  "expense_entries",
  {
    // Expense_ID, e.g. "EXP-xxxx".
    id: text("id").primaryKey(),
    orgId: text("org_id")
      .notNull()
      .references(() => organizations.id),
    entryDate: timestamp("entry_date", { withTimezone: true }).notNull().defaultNow(),
    categoryAccountId: text("category_account_id").notNull(),
    description: text("description").notNull().default(""),
    paidTo: text("paid_to").notNull().default(""),
    amount: numeric("amount").notNull(),
    attachmentUrl: text("attachment_url").notNull().default(""),
    createdBy: text("created_by").notNull().default(""),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [index("expense_entries_org_id_idx").on(table.orgId, table.entryDate)]
);

// PettyCashEntryRecord.Kind — TopUp moves money INTO Petty Cash from Cash/Bank (or another
// source); Expense moves money OUT of Petty Cash against an Expense category account. Same
// shape either way (a counter account + amount + description) so the book reads as one
// timeline, not two separate lists.
export const pettyCashKindEnum = pgEnum("petty_cash_kind", ["TopUp", "Expense"]);

/**
 * The Petty Cash Book (2026-09-24) — a small imprest cash fund, separate from the main
 * Cash/Bank account (its own `chart_of_accounts` Asset row, SYSTEM_ACCOUNT_CODES.PETTY_CASH),
 * topped up occasionally and spent from directly for small day-to-day cash expenses. Its
 * running balance is never stored here — same "derived, never stored" philosophy as every
 * other running total in this codebase (stock on-hand, order-reserved, customer outstanding)
 * — it's computed by summing this account's own `journal_lines` debit/credit, live, in
 * `src/lib/accounts/pettyCash.ts`.
 */
export const pettyCashEntries = pgTable(
  "petty_cash_entries",
  {
    // Petty_Cash_Entry_ID, e.g. "PCE-xxxx".
    id: text("id").primaryKey(),
    orgId: text("org_id")
      .notNull()
      .references(() => organizations.id),
    entryDate: timestamp("entry_date", { withTimezone: true }).notNull().defaultNow(),
    kind: pettyCashKindEnum("kind").notNull(),
    // TopUp: where the cash came from (normally Cash/Bank). Expense: which Expense category
    // it was spent against (Rent/Salary/Utilities/Misc, or any other Expense account).
    counterAccountId: text("counter_account_id").notNull(),
    description: text("description").notNull().default(""),
    amount: numeric("amount").notNull(),
    attachmentUrl: text("attachment_url").notNull().default(""),
    createdBy: text("created_by").notNull().default(""),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [index("petty_cash_entries_org_id_idx").on(table.orgId, table.entryDate)]
);

export const billPayments = pgTable(
  "bill_payments",
  {
    // Bill_Payment_ID, e.g. "BPY-xxxx".
    id: text("id").primaryKey(),
    orgId: text("org_id")
      .notNull()
      .references(() => organizations.id),
    billId: text("bill_id").notNull(),
    amount: numeric("amount").notNull(),
    mode: orderPaymentModeEnum("mode").notNull().default("Bank_Transfer"),
    reference: text("reference").notNull().default(""),
    paidAt: timestamp("paid_at", { withTimezone: true }).notNull().defaultNow(),
    recordedBy: text("recorded_by").notNull().default(""),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [index("bill_payments_org_id_bill_id_idx").on(table.orgId, table.billId)]
);

/**
 * Credit Notes (2026-09-24) — the reverse of an Invoice, against a real business event: a
 * Sales Return, a transit-loss write-off the customer shouldn't be billed for, or any other
 * reason the original invoiced value no longer stands. v1 is deliberately whole-invoice-level
 * (a single amount, not a line-item breakdown) — the same "narrow, seed-level" scope this
 * codebase's own Receivables started at. Always issued against exactly one existing `invoices`
 * row; `orderId`/`customerId` are denormalized from that invoice purely so a customer's own
 * credit balance can be queried without joining back through orders every time.
 *
 * Deliberately does NOT credit `Accounts Receivable` directly — see
 * SYSTEM_ACCOUNT_CODES.CUSTOMER_CREDIT_BALANCE's own comment in ledger.ts for why a separate
 * Liability account is correct here regardless of whether the original invoice was already
 * paid. Whether a Credit Note's value gets applied to a new order or refunded in cash is
 * decided later, per `credit_note_usages` below — a note itself is just the fact that this
 * much value was reversed, immutable once created (matches this schema's append-only-history
 * convention everywhere else: `lead_activities`, `order_activities`, journal entries, ...).
 */
export const creditNotes = pgTable(
  "credit_notes",
  {
    // Credit_Note_ID, e.g. "CRN-xxxx" — the real key. creditNoteNo is a separate,
    // sequential, customer-facing document number, same reasoning as invoices.invoiceNo.
    id: text("id").primaryKey(),
    orgId: text("org_id")
      .notNull()
      .references(() => organizations.id),
    invoiceId: text("invoice_id").notNull(),
    orderId: text("order_id").notNull(),
    customerId: text("customer_id").notNull(),
    creditNoteNo: text("credit_note_no").notNull().default(""),
    // REASONS ("Sales_Return" | "Transit_Loss" | "Price_Adjustment" | "Other") — closed but
    // not itself a Status column, kept text.
    reason: text("reason").notNull().default(""),
    amount: numeric("amount").notNull(),
    // GST portion of `amount` being reversed alongside it — capped to the original
    // invoice's own gstAmount, same capping reasoning as invoices.gstAmount itself.
    gstAmount: numeric("gst_amount").notNull().default("0"),
    attachmentUrl: text("attachment_url").notNull().default(""),
    createdBy: text("created_by").notNull().default(""),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    index("credit_notes_org_id_customer_id_idx").on(table.orgId, table.customerId),
    index("credit_notes_org_id_invoice_id_idx").on(table.orgId, table.invoiceId),
    // Real uniqueness, added 2026-09-24 to back createCreditNote()'s own retry-on-collision
    // loop — closes the gap allocateCreditNoteNumber()'s own header comment used to document
    // (no constraint meant a retry loop would have been dead code; see
    // src/lib/accounts/creditNotes.ts for the retry that now relies on this).
    unique("credit_notes_org_id_credit_note_no_unique").on(table.orgId, table.creditNoteNo),
  ]
);

// CreditNoteUsageRecord.Kind — Applied draws down the credit against a real order's own
// order_payments row (mode "Credit_Note"); Refunded pays it out in real cash. A credit
// note's own remaining balance is always `amount - sum(usages for that note)`, live-derived,
// never stored — same convention as every other running balance in this schema.
export const creditNoteUsageKindEnum = pgEnum("credit_note_usage_kind", ["Applied", "Refunded"]);

export const creditNoteUsages = pgTable(
  "credit_note_usages",
  {
    // Credit_Note_Usage_ID, e.g. "CNU-xxxx".
    id: text("id").primaryKey(),
    orgId: text("org_id")
      .notNull()
      .references(() => organizations.id),
    creditNoteId: text("credit_note_id").notNull(),
    kind: creditNoteUsageKindEnum("kind").notNull(),
    // Set only for "Applied" — which order this usage's value was credited against.
    orderId: text("order_id").notNull().default(""),
    amount: numeric("amount").notNull(),
    createdBy: text("created_by").notNull().default(""),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [index("credit_note_usages_org_id_credit_note_id_idx").on(table.orgId, table.creditNoteId)]
);

/**
 * Debit Notes (2026-09-24) — the Payables-side mirror of `creditNotes` above: a claim
 * against a Vendor instead of a reduction owed to a Customer. Built for IQC failures
 * specifically — a Failure Log entry (`failure_log`, src/db/schema/inward.ts) that the org
 * wants the vendor to compensate for, rather than (or alongside) accepting the failed
 * quantity into stock "Under Deviation" (that path writes a real stock_ledger "In" and
 * touches no accounting at all — see src/lib/inward/deviation.ts). Unlike `creditNotes`,
 * a Debit Note is NOT required to reference an existing Bill — a vendor Bill may not exist
 * yet at the point IQC fails a quantity (Bills happen later, against a Completed PO).
 *
 * Deliberately does NOT credit `Purchases / COGS` and debit `Accounts Payable` directly —
 * mirrors `creditNotes`' own reasoning exactly (see SYSTEM_ACCOUNT_CODES.
 * VENDOR_CLAIM_RECEIVABLE's own comment in ledger.ts): a Bill this claim relates to may
 * already be fully paid, so a new Asset account works uniformly for both cases. Whether the
 * claim later offsets a future Bill or is received back in real cash is decided at the point
 * of use (`debit_note_usages` below), not at issuance.
 */
export const debitNotes = pgTable(
  "debit_notes",
  {
    // Debit_Note_ID, e.g. "DBN-xxxx". debitNoteNo is a separate, sequential, human-facing
    // document number, same reasoning as invoices.invoiceNo/credit_notes.credit_note_no.
    id: text("id").primaryKey(),
    orgId: text("org_id")
      .notNull()
      .references(() => organizations.id),
    vendorId: text("vendor_id").notNull(),
    debitNoteNo: text("debit_note_no").notNull().default(""),
    // REASONS ("IQC_Fail" | "Other") — closed but not itself a Status column, kept text.
    reason: text("reason").notNull().default(""),
    // "" when not tied to a Failure Log entry at all (kept general on purpose, even though
    // the only issuance path built so far is from one).
    linkedFailureLogId: text("linked_failure_log_id").notNull().default(""),
    // Manually entered in full by whoever actually works the Failure Log entry — no
    // vendor-price auto-suggestion in this v1, per the user's own explicit choice.
    amount: numeric("amount").notNull(),
    attachmentUrl: text("attachment_url").notNull().default(""),
    createdBy: text("created_by").notNull().default(""),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    index("debit_notes_org_id_vendor_id_idx").on(table.orgId, table.vendorId),
    // Real uniqueness, added 2026-09-24 — same reasoning as
    // credit_notes_org_id_credit_note_no_unique above, mirrored for the Payables side.
    unique("debit_notes_org_id_debit_note_no_unique").on(table.orgId, table.debitNoteNo),
  ]
);

// DebitNoteUsageRecord.Kind — Applied draws the claim down against a real bill_payments row
// (mode "Debit_Note"); Received pays it back to the org in real cash. Same shape as
// creditNoteUsageKindEnum's own Applied/Refunded pair, mirrored for the opposite direction
// of money.
export const debitNoteUsageKindEnum = pgEnum("debit_note_usage_kind", ["Applied", "Received"]);

export const debitNoteUsages = pgTable(
  "debit_note_usages",
  {
    // Debit_Note_Usage_ID, e.g. "DNU-xxxx".
    id: text("id").primaryKey(),
    orgId: text("org_id")
      .notNull()
      .references(() => organizations.id),
    debitNoteId: text("debit_note_id").notNull(),
    kind: debitNoteUsageKindEnum("kind").notNull(),
    // Set only for "Applied" — which bill this usage's value was offset against.
    billId: text("bill_id").notNull().default(""),
    amount: numeric("amount").notNull(),
    createdBy: text("created_by").notNull().default(""),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [index("debit_note_usages_org_id_debit_note_id_idx").on(table.orgId, table.debitNoteId)]
);
