CREATE INDEX "report_shares_org_id_idx" ON "report_shares" USING btree ("org_id");--> statement-breakpoint
CREATE INDEX "users_org_id_idx" ON "users" USING btree ("org_id");--> statement-breakpoint
CREATE INDEX "recurring_tasks_org_id_idx" ON "recurring_tasks" USING btree ("org_id");--> statement-breakpoint
CREATE INDEX "tasks_org_id_idx" ON "tasks" USING btree ("org_id");--> statement-breakpoint
CREATE INDEX "tasks_org_id_assigned_to_idx" ON "tasks" USING btree ("org_id","assigned_to");--> statement-breakpoint
CREATE INDEX "failure_log_org_id_idx" ON "failure_log" USING btree ("org_id");--> statement-breakpoint
CREATE INDEX "ims_inward_org_id_idx" ON "ims_inward" USING btree ("org_id");--> statement-breakpoint
CREATE INDEX "inward_iqc_fms_org_id_idx" ON "inward_iqc_fms" USING btree ("org_id");--> statement-breakpoint
CREATE INDEX "bom_org_id_idx" ON "bom" USING btree ("org_id");--> statement-breakpoint
CREATE INDEX "indents_org_id_idx" ON "indents" USING btree ("org_id");--> statement-breakpoint
CREATE INDEX "items_org_id_idx" ON "items" USING btree ("org_id");--> statement-breakpoint
CREATE INDEX "stock_ledger_org_id_sku_idx" ON "stock_ledger" USING btree ("org_id","sku");--> statement-breakpoint
CREATE INDEX "plan_materials_org_id_idx" ON "plan_materials" USING btree ("org_id");--> statement-breakpoint
CREATE INDEX "production_plans_org_id_idx" ON "production_plans" USING btree ("org_id");--> statement-breakpoint
CREATE INDEX "fms_runs_org_id_instance_id_idx" ON "fms_runs" USING btree ("org_id","instance_id");--> statement-breakpoint
CREATE INDEX "fms_runs_org_id_context_ref_idx" ON "fms_runs" USING btree ("org_id","context_ref");--> statement-breakpoint
CREATE INDEX "fms_runs_org_id_template_id_status_idx" ON "fms_runs" USING btree ("org_id","template_id","status");--> statement-breakpoint
CREATE INDEX "fms_runs_org_id_assigned_to_status_idx" ON "fms_runs" USING btree ("org_id","assigned_to","status");--> statement-breakpoint
CREATE INDEX "fms_templates_org_id_idx" ON "fms_templates" USING btree ("org_id");--> statement-breakpoint
CREATE INDEX "fms_weekoff_overrides_org_id_idx" ON "fms_weekoff_overrides" USING btree ("org_id");--> statement-breakpoint
CREATE INDEX "leave_approval_steps_org_id_idx" ON "leave_approval_steps" USING btree ("org_id");--> statement-breakpoint
CREATE INDEX "leave_approvals_org_id_leave_id_idx" ON "leave_approvals" USING btree ("org_id","leave_id");--> statement-breakpoint
CREATE INDEX "leave_reassignments_org_id_leave_id_idx" ON "leave_reassignments" USING btree ("org_id","leave_id");--> statement-breakpoint
CREATE INDEX "leaves_org_id_status_idx" ON "leaves" USING btree ("org_id","status");--> statement-breakpoint
CREATE INDEX "leaves_org_id_doer_id_idx" ON "leaves" USING btree ("org_id","doer_id");--> statement-breakpoint
CREATE INDEX "customers_org_id_idx" ON "customers" USING btree ("org_id");--> statement-breakpoint
CREATE INDEX "vendor_items_org_id_idx" ON "vendor_items" USING btree ("org_id");--> statement-breakpoint
CREATE INDEX "vendors_org_id_idx" ON "vendors" USING btree ("org_id");--> statement-breakpoint
CREATE INDEX "purchase_order_lines_org_id_idx" ON "purchase_order_lines" USING btree ("org_id");--> statement-breakpoint
CREATE INDEX "purchase_orders_org_id_idx" ON "purchase_orders" USING btree ("org_id");--> statement-breakpoint
CREATE INDEX "lead_activities_org_id_lead_id_idx" ON "lead_activities" USING btree ("org_id","lead_id");--> statement-breakpoint
CREATE INDEX "leads_org_id_status_idx" ON "leads" USING btree ("org_id","status");--> statement-breakpoint
CREATE INDEX "quotation_items_org_id_idx" ON "quotation_items" USING btree ("org_id");--> statement-breakpoint
CREATE INDEX "quotations_org_id_status_idx" ON "quotations" USING btree ("org_id","status");--> statement-breakpoint
CREATE INDEX "order_activities_org_id_order_id_idx" ON "order_activities" USING btree ("org_id","order_id");--> statement-breakpoint
CREATE INDEX "order_items_org_id_sku_idx" ON "order_items" USING btree ("org_id","sku");--> statement-breakpoint
CREATE INDEX "order_payments_org_id_order_id_idx" ON "order_payments" USING btree ("org_id","order_id");--> statement-breakpoint
CREATE INDEX "orders_org_id_status_idx" ON "orders" USING btree ("org_id","status");--> statement-breakpoint
CREATE INDEX "pdi_activities_org_id_pdi_id_idx" ON "pdi_activities" USING btree ("org_id","pdi_id");--> statement-breakpoint
CREATE INDEX "pdi_inspections_org_id_order_id_idx" ON "pdi_inspections" USING btree ("org_id","order_id");--> statement-breakpoint
CREATE INDEX "tms_activities_org_id_order_id_idx" ON "tms_activities" USING btree ("org_id","order_id");--> statement-breakpoint
CREATE INDEX "tms_shipment_items_org_id_idx" ON "tms_shipment_items" USING btree ("org_id");--> statement-breakpoint
CREATE INDEX "tms_shipments_org_id_order_id_idx" ON "tms_shipments" USING btree ("org_id","order_id");--> statement-breakpoint
CREATE INDEX "tms_shipments_org_id_status_idx" ON "tms_shipments" USING btree ("org_id","status");--> statement-breakpoint
CREATE INDEX "transport_vendors_org_id_idx" ON "transport_vendors" USING btree ("org_id");--> statement-breakpoint
CREATE INDEX "bill_payments_org_id_bill_id_idx" ON "bill_payments" USING btree ("org_id","bill_id");--> statement-breakpoint
CREATE INDEX "bills_org_id_po_id_idx" ON "bills" USING btree ("org_id","po_id");--> statement-breakpoint
CREATE INDEX "invoices_org_id_order_id_idx" ON "invoices" USING btree ("org_id","order_id");--> statement-breakpoint
CREATE INDEX "journal_entries_org_id_entry_date_idx" ON "journal_entries" USING btree ("org_id","entry_date");--> statement-breakpoint
CREATE INDEX "journal_lines_org_id_idx" ON "journal_lines" USING btree ("org_id");--> statement-breakpoint
CREATE INDEX "dispatch_activities_org_id_order_id_idx" ON "dispatch_activities" USING btree ("org_id","order_id");--> statement-breakpoint
CREATE INDEX "dispatches_org_id_order_id_idx" ON "dispatches" USING btree ("org_id","order_id");--> statement-breakpoint
CREATE INDEX "payslips_org_id_user_id_idx" ON "payslips" USING btree ("org_id","user_id");--> statement-breakpoint
CREATE INDEX "salary_structures_org_id_user_id_idx" ON "salary_structures" USING btree ("org_id","user_id");