import { beforeEach, expect, it, vi } from "vitest";
const m = vi.hoisted(() => ({ read: vi.fn(), legacy: vi.fn(), tenantRun: vi.fn(), performance: vi.fn(), taskInputs: vi.fn(), cookieGet: vi.fn(), cookieSet: vi.fn() }));
vi.mock("@/lib/auth/guard", () => ({ requireSession: vi.fn(async () => ({ ok: false })) }));
vi.mock("next/headers", () => ({ cookies: async () => ({ get: m.cookieGet, set: m.cookieSet }) }));
vi.mock("@/lib/perf04-report-queries", () => ({ readPerf04ReportRows: m.read, readPerf04Performance: m.performance, readPerf04TaskInputs: m.taskInputs }));
vi.mock("@/lib/leads/leads", () => ({ listLeads: m.legacy }));
vi.mock("@/lib/tenant", () => ({ runWithTenant: m.tenantRun }));
vi.mock("@/lib/i18n/server", () => ({ getT: async () => (text: string) => text }));
vi.mock("@/db/client", () => { throw Error("No real DB imports allowed in report integration"); });
vi.mock("@/lib/tasks", () => ({ listTasks: vi.fn() }));
vi.mock("@/lib/auth/users", () => ({ listUsers: vi.fn(async () => []) }));
vi.mock("@/lib/recurringTasks", () => ({ listRecurringTasks: vi.fn() }));
vi.mock("@/lib/inward", () => ({ listInwardEntries: vi.fn(), listFailureLog: vi.fn(), listImsInward: vi.fn() }));
vi.mock("@/lib/fms/engine", () => ({ listAllFmsRuns: vi.fn(), isFmsStepOverdue: vi.fn() }));
vi.mock("@/lib/inventory/service", () => ({ getInventorySnapshot: vi.fn(), itemsNeedingReorder: vi.fn() }));
vi.mock("@/lib/inventory/indents", () => ({ listIndents: vi.fn() }));
vi.mock("@/lib/inventory/bom", () => ({ listBoms: vi.fn() }));
vi.mock("@/lib/inventory/plans", () => ({ listPlans: vi.fn() }));
vi.mock("@/lib/leave/leaves", () => ({ listAllLeaves: vi.fn() }));
vi.mock("@/lib/orders/orders", () => ({ listOrders: vi.fn() }));
vi.mock("@/lib/pdi/pdi", () => ({ listInspections: vi.fn() }));
vi.mock("@/lib/tms/tms", () => ({ listShipments: vi.fn() }));
vi.mock("@/lib/accounts/accounts", () => ({ listInvoices: vi.fn() }));
vi.mock("@/lib/accounts/payables", () => ({ listBills: vi.fn() }));
vi.mock("@/lib/dispatch/dispatch", () => ({ listDispatches: vi.fn() }));
vi.mock("@/lib/payroll/payroll", () => ({ listPayslipsForUser: vi.fn() }));
import Analytics from "@/app/dashboard/analytics";
import type { SessionPayload } from "@/lib/auth/session";
import type { TenantContext } from "@/lib/tenant";
const session = { userId: "USER-report", email: "report@example.test", role: "Admin", access: ["LEAD_FMS"] } as SessionPayload;
beforeEach(() => { vi.resetAllMocks(); m.read.mockResolvedValue([]); m.legacy.mockResolvedValue([]); m.tenantRun.mockImplementation((_tenant, fn) => fn()); });
it("single report invokes only its thin scoped query within explicit share tenant", async () => {
  const tenant = { orgId: "ORG-share" } as TenantContext;
  await Analytics({ session, rangeKey: "month", only: "leads", scope: "mine", tenant });
  expect(m.read).toHaveBeenCalledTimes(1);
  expect(m.read).toHaveBeenCalledWith("leads", expect.objectContaining({ key: "month" }), "mine", session);
  expect(m.legacy).not.toHaveBeenCalled(); expect(m.tenantRun).toHaveBeenCalledWith(tenant, expect.any(Function));
});
it("denied module does not call the report projection", async () => {
  await Analytics({ session: { ...session, access: [] }, rangeKey: "month", only: "leads" });
  expect(m.read).not.toHaveBeenCalled(); expect(m.legacy).not.toHaveBeenCalled();
});
it("performance requests a bounded SQL page rather than historical task/FMS lists", async () => {
  const viewer = { ...session, orgId: "ORG", access: ["PERFORMANCE_VIEW"] };
  m.performance.mockResolvedValue({ charts: [], rows: [], tasks: [], fmsRuns: [], page: 0, hasMore: false });
  await Analytics({ session: viewer, rangeKey: "month", only: "performance" });
  expect(m.performance).toHaveBeenCalledWith(expect.objectContaining({ key: "month" }), 0);
  expect(m.taskInputs).not.toHaveBeenCalled();
});
