/**
 * Every domain module an FMS step's "Existing FMS" data source (or a "lookup" form field
 * — see src/lib/fms/dataSource.ts's FormFieldLookup) can name as its source, along with
 * the column names it can pull.
 *
 * This used to be a bigger Sheets-era module registry (deleted in the Sheets-to-Postgres
 * cutover) that also carried a per-module setting key for the sheet URL an Admin pasted
 * in Settings, which no longer exists now that every module is a real table in the
 * shared schema. What survives here is purely the part of that registry the FMS
 * data-source picker actually needs: a stable key, a display label, and the column names
 * (unchanged from the old sheet headers — see each domain's own `*Record` type in
 * src/lib/fms/dataSourceResolver.ts) a template builder can offer to pull from.
 */
export interface SourceModuleDefinition {
  key: string;
  label: string;
  headers: string[];
}

export const SOURCE_MODULES: SourceModuleDefinition[] = [
  {
    key: "TASKS",
    label: "Tasks",
    headers: [
      "Task_ID",
      "Title",
      "Description",
      "Assigned_To",
      "Assigned_By",
      "Task_Type",
      "Recurrence_Frequency",
      "Due_Date",
      "Attachment_URL",
      "Status",
      "Completed_At",
      "Completion_Proof_URL",
      "Remark",
      "Created_At",
      "On_Time_Count",
      "Delay_Count",
      "Priority",
      "Recurring_ID",
    ],
  },
  {
    key: "RECURRING_TASKS",
    label: "Recurring Tasks (definitions)",
    headers: ["Recurring_ID", "Task", "Doer_ID", "Assigned_By", "Frequency", "Assign_Date", "Status", "Created_At"],
  },
  {
    key: "HOLIDAY_LIST",
    label: "Holiday List",
    headers: ["Date"],
  },
  {
    key: "INWARD_IQC_FMS",
    label: "Inward & IQC FMS",
    headers: [
      "Entry_ID",
      "Timestamp",
      "Party_Name",
      "Invoice_No",
      "Inward_Type",
      "Attachment_URL",
      "Remark",
      "IQC_Status",
      "Verified_By",
      "Verified_At",
      "Verify_Checkbox",
      "IQC_Pass_Qty",
      "IQC_Fail_Qty",
      "Fail_Reason",
      "SKU",
      "Item_Name",
      "Created_By",
      "IQC_TAT_Value",
      "IQC_TAT_Unit",
      "IQC_Deadline",
    ],
  },
  {
    key: "FAILURE_LOG",
    label: "Failure Log",
    headers: [
      "Log_ID",
      "Linked_Entry_ID",
      "Timestamp",
      "Party_Name",
      "Invoice_No",
      "Inward_Type",
      "Fail_Qty",
      "Fail_Reason",
      "Attachment_URL",
      "Verified_By",
    ],
  },
  {
    key: "IMS_INWARD",
    label: "IMS - Inward Sub-Sheet",
    headers: ["Record_ID", "Linked_Entry_ID", "Timestamp", "Party_Name", "Invoice_No", "Inward_Type", "Pass_Qty", "Verified_By"],
  },
  {
    key: "ITEMS",
    label: "Items (Inventory master)",
    headers: [
      "SKU",
      "Item_Name",
      "Category",
      "Size_Unit",
      "UOM",
      "Rate",
      "ADC_Manual",
      "Lead_Time_Days",
      "Safety_Factor",
      "MOQ",
      "Max_Level",
      "Location",
      "Status",
      "Created_At",
      "Created_By",
    ],
  },
  {
    key: "STOCK_LEDGER",
    label: "Stock Ledger",
    headers: ["Txn_ID", "Timestamp", "SKU", "Direction", "Quantity", "UOM", "Source", "Reference_ID", "Location", "Issued_To", "Remark", "User_ID"],
  },
  {
    key: "INDENTS",
    label: "Indents (Purchase requests)",
    headers: [
      "Indent_ID",
      "Timestamp",
      "SKU",
      "Item_Name",
      "Suggested_Qty",
      "Final_Qty",
      "UOM",
      "Reason",
      "Linked_Plan_ID",
      "Status",
      "Requested_By",
      "Approved_By",
      "Approved_At",
      "Expected_Date",
      "Received_Qty",
      "Received_At",
    ],
  },
  {
    key: "BOM",
    label: "BOM (Bill of Materials)",
    headers: [
      "BOM_ID",
      "Product_Name",
      "Product_SKU",
      "Version",
      "Line_No",
      "Component_SKU",
      "Component_Name",
      "Component_Type",
      "Qty_Per_Unit",
      "UOM",
      "Status",
      "Created_At",
      "Created_By",
    ],
  },
  {
    key: "PRODUCTION_PLANS",
    label: "Production Plans (PPC)",
    headers: [
      "Plan_ID",
      "Timestamp",
      "Product_Name",
      "Product_SKU",
      "BOM_ID",
      "BOM_Version",
      "Planned_Qty",
      "Production_Date",
      "Status",
      "Actual_Qty",
      "Started_By",
      "Started_At",
      "Created_By",
      "Notes",
      "Job_No",
      "Order_No",
      "FMS_Template_ID",
    ],
  },
  {
    key: "PLAN_MATERIALS",
    label: "Plan Materials (PPC)",
    headers: ["Plan_ID", "SKU", "Item_Name", "Qty_Per_Unit", "Required_Qty", "UOM", "Allocated_Qty", "Shortage_Qty", "Consumed_Qty", "Status", "Created_At"],
  },
  {
    key: "FMS_TEMPLATES",
    label: "FMS Templates",
    headers: [
      "Template_ID",
      "Template_Name",
      "Trigger_Event",
      "Status",
      "Created_By",
      "Created_At",
      "Step_No",
      "Step_Name",
      "Assigned_To",
      "TAT_Value",
      "TAT_Unit",
      "Outcome_Options",
      "Next_Step_Map",
      "Data_Source_Type",
      "Data_Source_Config",
      "Action_Type",
      "Action_Config",
      "Outcome_Type",
      "TAT_Source_Step_No",
      "TAT_Source_Field_Key",
      "TAT_Offset",
    ],
  },
  {
    key: "FMS_RUNS",
    label: "FMS Runs",
    headers: [
      "Run_ID",
      "Instance_ID",
      "Template_ID",
      "Template_Name",
      "Context_Ref",
      "Started_By",
      "Started_At",
      "Step_No",
      "Step_Name",
      "Assigned_To",
      "Created_At",
      "TAT_Start",
      "TAT_Deadline",
      "Completed_At",
      "Completed_By",
      "Outcome",
      "Status",
      "Remark",
      "Form_Data",
      "Quantity",
    ],
  },
  {
    key: "FMS_WEEKOFF_OVERRIDES",
    label: "FMS Week-off Overrides",
    headers: ["Override_ID", "Date", "Scope", "Scope_Value", "Created_By", "Created_At"],
  },
  {
    key: "VENDORS",
    label: "Vendor Master",
    headers: [
      "Vendor_ID",
      "Vendor_Name",
      "Contact_Person",
      "Phone",
      "Email",
      "GSTIN",
      "Address",
      "City",
      "State",
      "Payment_Terms",
      "Bank_Name",
      "Bank_Account_No",
      "IFSC",
      "Status",
      "Created_At",
      "Created_By",
    ],
  },
  {
    key: "CUSTOMERS",
    label: "Customer Master",
    headers: [
      "Customer_ID",
      "Customer_Name",
      "Contact_Person",
      "Phone",
      "Email",
      "GSTIN",
      "Billing_Address",
      "Shipping_Address",
      "City",
      "State",
      "Credit_Terms",
      "Status",
      "Created_At",
      "Created_By",
    ],
  },
];

export function getSourceModuleDefinition(moduleKey: string): SourceModuleDefinition | null {
  return SOURCE_MODULES.find((m) => m.key === moduleKey) ?? null;
}
